package: notification 
version: '1.0.0' 
author: 'Alexander Walther' 
supportpage: https://github.com/alexplusde/notification 


requires:                       
    php:
        version: '>7.3,<9'
    redaxo: ^5.13              
    packages:                  
        yform: "^4"



page:
    title: translate:notification_title    
    prio: 100                       
    icon: rex-icon fa-gear

pages:
    notification: 
        title: translate:notification_title

        block: system               
        prio: 15                    
        icon: rex-icon fa-calendar  
        perm: notification[]               
        subpages:                   
            table:
                title: translate:notification_settings
                icon: rex-icon fa-gear
                itemclass: pull-right
                perm: admin
            settings:
                title: translate:notification_settings
                icon: rex-icon fa-gear
                itemclass: pull-right
                perm: admin
            docs:
                title: translate:notification_docs
                subPath: README.md  
                icon: rex-icon fa-info-circle
                itemclass: pull-right
                perm: notification[docs]

default_config:
    editor: 'Test' 
